### ISSUE TITLE
myLog after accepting the call

### ISSUE THREAD

**Issue by legendvijay** [YK-Unit/AppRTCDemo#13]
视频不是流，请给一些建议

VAdapt Frame: 0 / 600 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false
Jingle:Port[audio:1:0::Net[en0:192.168.1.0/24]]: Port deleted
Jingle:Port[audio:1:0::Net[en0:192.168.1.0/24]]: Removed port from allocator (2 remaining)
Removed port from p2p socket: 2 remaining
VAdapt Frame: 0 / 900 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false
Jingle:Port[audio:1:0:relay:Net[en0:192.168.1.0/24]]: Port deleted
Jingle:Port[audio:1:0:relay:Net[en0:192.168.1.0/24]]: Removed port from allocator (1 remaining)
Removed port from p2p socket: 1 remaining
Jingle:Port[audio:1:0:local:Net[en0:192.168.1.0/24]]: Port deleted
Jingle:Port[audio:1:0:local:Net[en0:192.168.1.0/24]]: Removed port from allocator (0 remaining)
Removed port from p2p socket: 0 remaining
VAdapt Frame: 0 / 1200 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false
VAdapt Frame: 0 / 1500 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false
VAdapt Frame: 0 / 1800 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false
VAdapt Frame: 0 / 2100 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false
VAdapt Frame: 0 / 2400 Changes: 0 Input: 192x144 Scale: 1 Output: 192x144 Changed: false

**Comment by teo029** [comment]
Have you solved this?

**Comment by wenghengcong** [comment]
I also have this problem.
After change the two devices internet to LAN(may be the same wifi),it works!
you can have a try.

**Comment by legendvijay** [comment]
then add turn server

**Comment by YK-Unit** [comment]
如果你没有可用的STUN/TURN服务器，建议你在局域网中（同一个WIFI）下进行测试。
